// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
  'aws_project_region': 'eu-central-1',
  'aws_cognito_identity_pool_id': 'eu-central-1:12bcecc2-96b4-4979-ae33-befc44b4b75a',
  'aws_cognito_region': 'eu-central-1',
  'aws_user_pools_id': 'eu-central-1_bVFNjHsan',
  'aws_user_pools_web_client_id': '6uk37h416t4ndf8pp9vmgmf54u',
  'oauth': {
    'domain': 'auth.uafine.com',
    'scope': [
      'email',
      'openid',
      'profile',
      'aws.cognito.signin.user.admin'
    ],
    'redirectSignIn': 'https://www.uafine.com/login',
    'redirectSignOut': 'https://www.uafine.com/auth',
    'responseType': 'code'
  },

  'federationTarget': 'COGNITO_USER_POOLS'
};


export default awsmobile;
